insert into usr (username, first_name, last_name, gender) values ('rsenechault0', 'Robers', 'Senechault', 'MALE');
insert into usr (username, first_name, last_name, gender) values ('bfuxman1', 'Beryle', 'Fuxman', 'FEMALE');
insert into usr (username, first_name, last_name, gender) values ('bdalyell2', 'Berenice', 'Dalyell', 'FEMALE');
insert into usr (username, first_name, last_name, gender) values ('dcraigheid3', 'Dulcine', 'Craigheid', 'FEMALE');
insert into usr (username, first_name, last_name, gender) values ('rgjerde4', 'Rheba', 'Gjerde', 'FEMALE');
insert into usr (username, first_name, last_name, gender) values ('btoman5', 'Brett', 'Toman', 'FEMALE');
insert into usr (username, first_name, last_name, gender) values ('agrishenkov6', 'Alvera', 'Grishenkov', 'FEMALE');
insert into usr (username, first_name, last_name, gender) values ('pgandey7', 'Paloma', 'Gandey', 'FEMALE');
insert into usr (username, first_name, last_name, gender) values ('awonham8', 'Alix', 'Wonham', 'MALE');
insert into usr (username, first_name, last_name, gender) values ( 'lcovey9', 'Lilith', 'Covey', 'FEMALE');

insert into usr_order (usr_id, name, comment, price, order_date) values (8, 'Thia', 'Orange', 87.34, '2023-07-08');
insert into usr_order (usr_id, name, comment, price, order_date) values (2, 'Janeta', 'Aquamarine', 68.72, '2023-05-12');
insert into usr_order (usr_id, name, comment, price, order_date) values (9, 'Pate', 'Violet', 12.9, '2023-03-13');
insert into usr_order (usr_id, name, comment, price, order_date) values (1, 'Miller', 'Green', 93.82, '2023-04-23');
insert into usr_order (usr_id, name, comment, price, order_date) values (5, 'Lockwood', 'Puce', 29.63, '2023-07-26');
insert into usr_order (usr_id, name, comment, price, order_date) values (4, 'Ludovika', 'Goldenrod', 40.51, '2023-10-05');
insert into usr_order (usr_id, name, comment, price, order_date) values (7, 'Charlene', 'Blue', 11.89, '2023-10-09');
insert into usr_order (usr_id, name, comment, price, order_date) values (6, 'Beth', 'Pink', 26.62, '2023-08-03');
insert into usr_order (usr_id, name, comment, price, order_date) values (2, 'Gerrie', 'Yellow', 69.23, '2023-02-02');
insert into usr_order (usr_id, name, comment, price, order_date) values (5, 'Gweneth', 'Goldenrod', 32.99, '2023-03-30');
insert into usr_order (usr_id, name, comment, price, order_date) values (2, 'Filip', 'Khaki', 41.65, '2022-11-17');
insert into usr_order (usr_id, name, comment, price, order_date) values (1, 'Daniela', 'Goldenrod', 48.33, '2022-12-31');
insert into usr_order (usr_id, name, comment, price, order_date) values (10, 'Kimberley', 'Fuscia', 8.84, '2023-02-18');
insert into usr_order (usr_id, name, comment, price, order_date) values (5, 'Marylee', 'Orange', 27.22, '2022-11-09');
insert into usr_order (usr_id, name, comment, price, order_date) values (8, 'Aurilia', 'Maroon', 12.27, '2023-07-07');
insert into usr_order (usr_id, name, comment, price, order_date) values (9, 'Waring', 'Puce', 32.67, '2023-06-17');
insert into usr_order (usr_id, name, comment, price, order_date) values (10, 'Aleksandr', 'Maroon', 60.25, '2023-10-10');
insert into usr_order (usr_id, name, comment, price, order_date) values (5, 'Felicio', 'Orange', 12.59, '2023-04-27');
insert into usr_order (usr_id, name, comment, price, order_date) values (9, 'Osbourne', 'Pink', 12.31, '2023-05-30');
insert into usr_order (usr_id, name, comment, price, order_date) values (3, 'Dawn', 'Yellow', 43.76, '2023-10-04');