insert into usr (username, first_name, last_name, gender) values ('rsenechault0', 'Robers', 'Senechault', 'Male');
insert into usr (username, first_name, last_name, gender) values ('bfuxman1', 'Beryle', 'Fuxman', 'Female');
insert into usr (username, first_name, last_name, gender) values ('bdalyell2', 'Berenice', 'Dalyell', 'Female');
insert into usr (username, first_name, last_name, gender) values ('dcraigheid3', 'Dulcine', 'Craigheid', 'Female');
insert into usr (username, first_name, last_name, gender) values ('rgjerde4', 'Rheba', 'Gjerde', 'Female');
insert into usr (username, first_name, last_name, gender) values ('btoman5', 'Brett', 'Toman', 'Female');
insert into usr (username, first_name, last_name, gender) values ('agrishenkov6', 'Alvera', 'Grishenkov', 'Female');
insert into usr (username, first_name, last_name, gender) values ('pgandey7', 'Paloma', 'Gandey', 'Female');
insert into usr (username, first_name, last_name, gender) values ('awonham8', 'Alix', 'Wonham', 'Male');
insert into usr (username, first_name, last_name, gender) values ( 'lcovey9', 'Lilith', 'Covey', 'Female');

insert into usr_order (usr_id, name, comment, price, order_date) values (1, 9, 'Goldenrod', 16.94, '5/26/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (2, 3, 'Goldenrod', 67.03, '8/22/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (3, 4, 'Orange', 29.54, '9/13/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (4, 4, 'Puce', 71.62, '2/28/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (5, 2, 'Purple', 13.24, '8/9/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (6, 5, 'Blue', 94.93, '6/29/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (7, 8, 'Crimson', 37.12, '8/14/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (8, 1, 'Pink', 71.06, '8/19/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (9, 7, 'Indigo', 67.93, null);
insert into usr_order (usr_id, name, comment, price, order_date) values (10, 1, 'Turquoise', 6.67, '5/28/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (11, 8, 'Pink', null, '12/14/2022');
insert into usr_order (usr_id, name, comment, price, order_date) values (12, 7, 'Teal', 36.35, '1/20/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (13, 3, 'Purple', 70.92, '2/4/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (14, 1, 'Yellow', 78.1, '10/4/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (15, 6, 'Fuscia', 61.12, null);
insert into usr_order (usr_id, name, comment, price, order_date) values (16, 2, 'Fuscia', 9.4, '1/30/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (17, 8, 'Khaki', 31.01, '11/17/2022');
insert into usr_order (usr_id, name, comment, price, order_date) values (18, 6, 'Aquamarine', 37.44, '9/25/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (19, 7, 'Pink', 53.07, '5/21/2023');
insert into usr_order (usr_id, name, comment, price, order_date) values (20, 3, 'Goldenrod', 94.8, '8/26/2023');